### PR TITLE
chore(deps): update to polkadot-v0.9.12

### PR DESCRIPTION
**Pull request by mattsse**
## Changes

- Update everything

For some reason, cargo fails to apply the patches properly so the build ends up with, it's not obvious to me where this originates...

```sh
 warning: Patch `cumulus-client-cli v0.1.0 (https://github.com/paritytech//cumulus?rev=f5926c2f50df73bf36171b138241437131d76fff#f5926c2f)` was not used in the crate graph.
  Patch `cumulus-client-collator v0.1.0 (https://github.com/paritytech//cumulus?rev=f5926c2f50df73bf36171b138241437131d76fff#f5926c2f)` was not used in the crate graph.
  Patch `cumulus-client-consensus-aura v0.1.0 (https://github.com/paritytech//cumulus?rev=f5926c2f50df73bf36171b138241437131d76fff#f5926c2f)` was not used in the crate graph.
  Patch `cumulus-client-consensus-common v0.1.0 (https://github.com/paritytech//cumulus?rev=f5926c2f50df73bf36171b138241437131d76fff#f5926c2f)` was not used in the crate graph.
  Patch `cumulus-client-consensus-relay-chain v0.1.0 (https://github.com/paritytech//cumulus?rev=f5926c2f50df73bf36171b138241437131d76fff#f5926c2f)` was not used in the crate graph.
  Patch `cumulus-client-network v0.1.0 (https://github.com/paritytech//cumulus?rev=f5926c2f50df73bf36171b138241437131d76fff#f5926c2f)` was not used in the crate graph.
  Patch `cumulus-client-service v0.1.0 (https://github.com/paritytech//cumulus?rev=f5926c2f50df73bf36171b138241437131d76fff#f5926c2f)` was not used in the crate graph.
  Patch `frame-benchmarking v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `frame-benchmarking-cli v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `frame-try-runtime v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-authority-discovery v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-babe v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-bounties v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-democracy v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-election-provider-multi-phase v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-elections-phragmen v5.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-grandpa v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-identity v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-im-online v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-indices v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-membership v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-mmr v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-mmr-primitives v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-mmr-rpc v3.0.0 (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-multisig v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-nicks v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-offences v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-offences-benchmarking v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-proxy v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-recovery v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-scheduler v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-session-benchmarking v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-society v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-staking-reward-curve v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-tips v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-transaction-payment-rpc v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-treasury v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-utility v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `pallet-vesting v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `remote-externalities v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-authority-discovery v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-basic-authorship v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-block-builder v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-chain-spec v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-cli v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-client-api v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-client-db v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-consensus v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-consensus-aura v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-consensus-babe v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-consensus-babe-rpc v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-consensus-epochs v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-consensus-manual-seal v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-consensus-slots v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-executor v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-executor-common v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-executor-wasmtime v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-finality-grandpa v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-finality-grandpa-rpc v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-informant v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-keystore v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-network v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-network-gossip v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-offchain v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-rpc v4.0.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-rpc-api v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.
  Patch `sc-service v0.10.0-dev (https://github.com/paritytech//substrate?rev=d76f39995315ec36980908e4b99709bd14927044#d76f3999)` was not used in the crate graph.

  error[E0277]: the trait bound `XcmExecutor<XcmConfig>: xcm::v1::ExecuteXcm<Call>` is not satisfied
     --> /Users/Matthias/git/rust/PINT/runtime/dev/src/lib.rs:686:2
      |
  686 |     type XcmExecutor = XcmExecutor<XcmConfig>;
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `xcm::v1::ExecuteXcm<Call>` is not implemented for `XcmExecutor<XcmConfig>`
      |
  note: required by a bound in `pallet_remote_asset_manager::Config::XcmExecutor`
     --> /Users/Matthias/git/rust/PINT/pallets/remote-asset-manager/src/lib.rs:139:21
      |
  139 |         type XcmExecutor: ExecuteXcm<<Self as frame_system::Config>::Call>;
      |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `pallet_remote_asset_manager::Config::XcmExecutor`

  error[E0277]: the trait bound `ParentAsUmp<cumulus_pallet_parachain_system::Pallet<Runtime>, pallet_xcm::Pallet<Runtime>>: xcm::v1::SendXcm` is not satisfied
     --> /Users/Matthias/git/rust/PINT/runtime/dev/src/lib.rs:690:2
      |
  690 |     type XcmSender = XcmRouter;
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `xcm::v1::SendXcm` is not implemented for `ParentAsUmp<cumulus_pallet_parachain_system::Pallet<Runtime>, pallet_xcm::Pallet<Runtime>>`
      |
      = note: required because of the requirements on the impl of `xcm::v1::SendXcm` for `(ParentAsUmp<cumulus_pallet_parachain_system::Pallet<Runtime>, pallet_xcm::Pallet<Runtime>>, cumulus_pallet_xcmp_queue::Pallet<Runtime>)`
  note: required by a bound in `pallet_remote_asset_manager::Config::XcmSender`
     --> /Users/Matthias/git/rust/PINT/pallets/remote-asset-manager/src/lib.rs:149:19
      |
  149 |         type XcmSender: SendXcm;
      |                         ^^^^^^^ required by this bound in `pallet_remote_asset_manager::Config::XcmSender`

  error[E0277]: the trait bound `cumulus_pallet_xcmp_queue::Pallet<Runtime>: xcm::v1::SendXcm` is not satisfied
     --> /Users/Matthias/git/rust/PINT/runtime/dev/src/lib.rs:690:2
      |
  690 |     type XcmSender = XcmRouter;
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `xcm::v1::SendXcm` is not implemented for `cumulus_pallet_xcmp_queue::Pallet<Runtime>`
      |
      = note: required because of the requirements on the impl of `xcm::v1::SendXcm` for `(ParentAsUmp<cumulus_pallet_parachain_system::Pallet<Runtime>, pallet_xcm::Pallet<Runtime>>, cumulus_pallet_xcmp_queue::Pallet<Runtime>)`
  note: required by a bound in `pallet_remote_asset_manager::Config::XcmSender`
     --> /Users/Matthias/git/rust/PINT/pallets/remote-asset-manager/src/lib.rs:149:19
      |
  149 |         type XcmSender: SendXcm;
      |                         ^^^^^^^ required by this bound in `pallet_remote_asset_manager::Config::XcmSender`

```

## Tests

```

```

## Issues

-

### CODE REVIEW

**Comment by clearloop** [comment]
now it is xcm::v2 

=.=

**Review by clearloop — CHANGES_REQUESTED** [review]
update the imports of xcm package in `xcm-executor` to `xcm::latest` instead of `xcm::v1` can solve this, but there're more issues with the `node/client`, tried on my local machine

**Comment by mattsse** [comment]
yeah there were breaking changes in the executor

**Comment by clearloop** [comment]
currently could not build with `cargo b` as well, seems some features in `**/*Cargo.tml` are missing

**Comment by mattsse** [comment]
building works on my machine and CI, but the one test keeps failing

**Comment by clearloop** [comment]
> building works on my machine and CI, but the one test keeps failing

https://app.circleci.com/jobs/github/ChainSafe/PINT/7691?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

`cargo b` works as well?

**Comment by clearloop** [comment]
aswsome! 

so, it is a fee issue?

**Review by clearloop — APPROVED** [review]

**Comment by mattsse** [comment]
> awesome!
> 
> so, it is a fee issue?

yeah it was a nightmare to debug because somehow the compiler always panics if it isn't cleaned first...

**Comment by clearloop** [comment]
> yeah it was a nightmare to debug because somehow the compiler always panics if it isn't cleaned first...

exactly...every time changing a single, need to `cargo clean && cargo t` =.=

**Comment by mattsse** [comment]
> > yeah it was a nightmare to debug because somehow the compiler always panics if it isn't cleaned first...
> 
> exactly...every time changing a single file, need to `cargo clean && cargo t` =.=

same thing with SKIP_WASM_BUILD...

**Comment by mattsse** [comment]
@clearloop seems like some e2e were Hit, could be metadata related?
voting to merge this as is and follow up with a test fix?

**Pull request merged**
