### PR TITLE
chore: upgrade to polkadot 0.9.4

### LINKED ISSUE #103: Update rococo-v1 -> polkadot-v0.9.3
## Issue summary

- See https://github.com/substrate-developer-hub/substrate-parachain-template/pull/33

## Other information and links

-

### PR DESCRIPTION
**Pull request by mattsse**
## Changes

- update runtime and node to reflect latest changes
- patches substrate/polkadot/cumulus deps
- Use compact Cargo.toml for every pallet

The patches are necessary:
- patching `chainlink-feed` pallet
- ~~patching `jsonrpc*-alpha` versions that always get pulled in and break stuff~~

## Tests

```
cargo t
```

## Issues

- Closes #103

### CODE REVIEW

**Comment by mattsse** [comment]
The CI apparently fails to download the patches, `paritytech//substrate is not a valid repository name`
However the double slashes are necessary so that cargo can resolve all of them properly: https://github.com/rust-lang/cargo/issues/5478#issuecomment-387171359

**Comment by clearloop** [comment]
Let me run tests on my machine

**Review by clearloop — COMMENTED** [review]
Wierd on my machine

```
$ cargo t
  warning: use of deprecated type alias `pallet_staking::Module`: use `Pallet` instead
    --> /Users/clearloop/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/55be325/runtime/parachains/src/reward_points.rs:57:4
     |
  57 |         <pallet_staking::Module<C>>::reward_by_ids(rewards);
     |          ^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: `#[warn(deprecated)]` on by default

  warning: 1 warning emitted

     Compiling polkadot-runtime-common v0.9.4 (/Users/clearloop/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/55be325/runtime/common)
  error[E0046]: not all trait items implemented, missing: `transfer_all`
    --> /Users/clearloop/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/55be325/runtime/polkadot/src/weights/pallet_balances.rs:45:1
     |
  45 | impl<T: frame_system::Config> pallet_balances::WeightInfo for WeightInfo<T> {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `transfer_all` in implementation
     |
     = help: implement the missing item: `fn transfer_all() -> u64 { todo!() }`

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0046`.
  error: could not compile `polkadot-runtime`
```

```
$ cargo t --all-features
error: failed to run custom build command for `parachain-runtime v2.0.0 (/Users/clearloop/code/PINT/runtime)`

Caused by:
  process didn't exit successfully: `/Users/clearloop/code/PINT/target/debug/build/parachain-runtime-e0e3cd16d0f6f688/build-script-build` (exit code: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "/Users/clearloop/.rustup/toolchains/nightly-2021-03-13-aarch64-apple-darwin/bin/cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/clearloop/code/PINT/target/debug/wbuild/parachain-runtime/Cargo.toml" "--color=always" "--release"
  Using rustc version: rustc 1.52.0-nightly (b3e19a221 2021-03-12)


  --- stderr
      Blocking waiting for file lock on package cache
  error: failed to select a version for `pallet-committee`.
      ... required by package `parachain-runtime v2.0.0 (/Users/clearloop/code/PINT/runtime)`
      ... which is depended on by `parachain-runtime-wasm v1.0.0 (/Users/clearloop/code/PINT/target/debug/wbuild/parachain-runtime)`
  versions that meet the requirements `=0.0.1` are: 0.0.1

  the package `parachain-runtime` depends on `pallet-committee`, with features: `sp-runtime` but `pallet-committee` does not have these features.


  failed to select a version for `pallet-committee` which could resolve this conflict
```
```

**Comment by mattsse** [comment]
seems like the jsonrpc issues are resolve, patched it against 0.9.4.
`cargo t --all-features` should succeed now. 
curious why the ci fails to fetch the patches.

**Comment by clearloop** [comment]
```
$ cargo t 
error[E0599]: no variant or associated item named `Committee` found for enum `mock::Event` in the current scope
   --> pallets/committee/src/tests.rs:491:23
    |
491 |           if let Event::Committee(crate::Event::Proposed(_, _, hash)) = last_event() {
    |                         ^^^^^^^^^ variant or associated item not found in `mock::Event`
    | 
   ::: pallets/committee/src/mock.rs:26:1
    |
26  | / frame_support::construct_runtime!(
27  | |     pub enum Test where
28  | |         Block = Block,
29  | |         NodeBlock = Block,
...   |
34  | |     }
35  | | );
    | |__- variant or associated item `Committee` not found here
```

```
$ cargo t --all-features
error[E0277]: the trait bound `(): pallet_chainlink_feed::WeightInfo` is not satisfied
   --> pallets/price-feed/src/mock.rs:109:5
    |
109 |     type WeightInfo = ();
    |     ^^^^^^^^^^^^^^^^^^^^^ the trait `pallet_chainlink_feed::WeightInfo` is not implemented for `()`
    | 
   ::: /Users/clearloop/.cargo/git/checkouts/chainlink-polkadot-9ffdf632331b9d0f/486bf07/pallet-chainlink-feed/src/lib.rs:322:26
    |
322 |         type WeightInfo: WeightInfo;
    |                          ---------- required by this bound in `pallet_chainlink_feed::Config::WeightInfo`

   Compiling polkadot-node-primitives v0.1.0 (https://github.com/paritytech//polkadot?rev=2f28561a09aab0613b5f8a68fbabf723d5fc197e#2f28561a)
error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `pallet-price-feed`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0599]: no variant or associated item named `Committee` found for enum `mock::Event` in the current scope
   --> pallets/committee/src/tests.rs:491:23
    |
491 |           if let Event::Committee(crate::Event::Proposed(_, _, hash)) = last_event() {
    |                         ^^^^^^^^^ variant or associated item not found in `mock::Event`
    | 
   ::: pallets/committee/src/mock.rs:26:1
    |
26  | / frame_support::construct_runtime!(
27  | |     pub enum Test where
28  | |         Block = Block,
29  | |         NodeBlock = Block,
...   |
34  | |     }
35  | | );
    | |__- variant or associated item `Committee` not found here


```

**Comment by mattsse** [comment]
These should be fixed now,
Any ideas wrt #112 ?

**Comment by clearloop** [comment]
Build pass on my machine in 7c2af9f

**Review by clearloop — APPROVED** [review]

**Comment by mattsse** [comment]
FYI running this currently fails due to missing validators, and requires #109 to fix. Currently working on this.

**Pull request merged**
