### PR TITLE
chore: upgrade to polkadot v0.9.9 and xcm

### LINKED ISSUE #260: Support XCM v1
## Issue summary

- [ ] Update substrate + polkadot (0.9.9), which will introduce v1
- [ ] use `xcm::latest`
- [ ] rename all types accordingly
- [ ] Make `Location::Null` a noop

## Other information and links

-  https://github.com/paritytech/polkadot/pull/2815#issuecomment-893297725

### PR DESCRIPTION
**Pull request by mattsse**
## Changes

- update all patches
- enable max-encode-len feature for codec
- fix breaking issues
- ~~upgrade xcm latest~~ will be included in upcoming polkadot branches

## Tests

```

```

## Issues

- Closes #260

### CODE REVIEW

**Comment by clearloop** [comment]
Lint and test not passed

**Comment by mattsse** [comment]
> Lint and test not passed

yeah missed some changes in runtime benchmarks

**Comment by mattsse** [comment]
@clearloop `cargo t --all-features` currently breaks due to some snafu in polkadot-testruntime that has been resolved on master. wonder whether we should only test --all-features for runtimes?

**Comment by clearloop** [comment]
> @clearloop `cargo t --all-features` currently breaks due to some snafu in polkadot-testruntime that has been resolved on master. wonder whether we should only test --all-features for runtimes?

I'm okay with this, but we might need to open and issue to trace this bug

**Review by clearloop — APPROVED** [review]

**Pull request merged**
