### PR TITLE
Complete e2e tests for single call APIs

### PR DESCRIPTION
**Pull request by clearloop**
## Changes

- [x] local_treasury
- [x] price_feed
- [x] saft_registry

## Tests

The tests of `remote-asset-manager` and `committee` and `asset-index` are complex, 

- `asset-index` is in completed
- For `remote-asset-manager`, I don't have ideas now
- I will handle the test of `committee` in next pull request

```
CI
```

https://circleci.com/gh/ChainSafe/PINT/1836?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

## Issues

Ref #81

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
LGTM, but should we also generate js bindings at some point?

**Review by mattsse — APPROVED** [review]

**Comment by clearloop** [comment]
> LGTM, but should we also generate js bindings at some point?

Do you mean doing this https://polkadot.js.org/docs/api/examples/promise/typegen/ in PINT also?

**Comment by mattsse** [comment]
Could be potentially useful for other services as well, not limited to e2e tests

**Comment by clearloop** [comment]
> Could be potentially useful for other services as well, not limited to e2e tests

I agree with this, I was considering just write them into our repo or fetching and building metadata from a long-existing node of PINT

**Pull request merged**
