### PR TITLE
fix: relative img path

### PR DESCRIPTION
**Pull request by mattsse**
## Changes

- use correct relative path for nav formula png

## Tests

```

```

## Issues

-

### CODE REVIEW

**Comment by clearloop** [comment]
broken in https://github.com/ChainSafe/PINT/blob/matt/fix-relaive-path/docs/getting-started/overview/architecture.md

**Comment by mattsse** [comment]
I see, I guess mkdocs and github handle relative paths differently...

**Review by clearloop — APPROVED** [review]
Could be merged if the website go first

**Comment by mattsse** [comment]
> Could be merged if the website go first

yeah let's prioritize that

**Pull request merged**
