### PR TITLE
feat(js): adds scripts in js directory

### LINKED ISSUE #337: Adds scripts exporting types.json to resources
## Issue summary

`resources/types.json` is extracted from `js/pint-types/bundle/index.ts`, we can write a script updating this file automatically, in case our types are really simple currently, we might can write a rust script in `build.rs`, match and export the types from `pint-types-bundle`

Or maybe a command of `pint-types-bundle` is enough

## Other information and links

-

### PR DESCRIPTION
**Pull request by clearloop**
## Changes

- update `/resources/types.json` with script `update-pint-types`
- run e2e tests with script `e2e`

## Tests

```
cd js && yarn 

# updates types
yarn update-pint-types

# run e2e tests
yarn e2e
```

## Issues

- Closes #337

### CODE REVIEW

**Comment by clearloop** [comment]
The `resources/types.json` contains the types of `chainlink-feed` also?

**Comment by mattsse** [comment]
> The `resources/types.json` contains the types of `chainlink-feed` also?

yes

**Comment by clearloop** [comment]
> > The `resources/types.json` contains the types of `chainlink-feed` also?
> 
> yes

pint-types seems already can support the polkadot-js UI ( tried on my local machine ), should we still embed the types of chainlink in our `types.json`? 

If developers construct their polkadot-js API they might want to 

```
import PINTtype from "@pint/types"
import ChainlinkFeedTypes from "@chainlink-feed/types"
```

**Review by mattsse — APPROVED** [review]
lgtm

**Pull request merged**
