### PR TITLE
feat(docs): Adds mkdocs for project documentation 

### PR DESCRIPTION
**Pull request by dutterbutter**
## Changes

Builds off of documentation from #330 

- Adds `docs` dir which contains documentation sections
- Adds docs github action workflow
- 

## TODO

- [x] Outline CLI commands in `docs/usage/command-line.md`
- [x] Outline configuration options in `docs/usage/configuration.md`
- [ ] Add and reference `contributions.md` file
- [ ] Outline steps and images for interacting with PINT using polkadot.js ui 
- [x] Add documentation for running test suite and debugging
- [x] Update and add documentation for running PINT using docker

## Tests

```
mkdocs serve
```
Visit `http://127.0.0.1:8000/`

## Issues

- Related to #224

### CODE REVIEW

**Review by Redoudou — APPROVED** [review]
Thank you guys

**Review by mattsse — APPROVED** [review]

**Review by mattsse — CHANGES_REQUESTED** [review]
Nice,
@clearloop can you perhaps add a brief overview of:
* what is e2e?
* what purpose?

So that it's clear that this is intended for cross chain  testing

**Review by mattsse — APPROVED** [review]

**Review by clearloop — APPROVED** [review]

**Comment by clearloop** [comment]
Should we add a chapter of debugging and introduce `root call`? most of the calls of PINT can not run independent before adding asset ( create a feed first )

**Comment by mattsse** [comment]
> Should we add a chapter of debugging and introduce `root call`? most of the calls of PINT can not run independent before adding asset ( or creating a feed first )

I'll describe these in a dedicated section that describeds the asset-index logic

**Review by mattsse — APPROVED** [review]
lgtm

**Pull request merged**
