### PR TITLE
feat(derive): extend xcm errors with proc-macro for reversed usages

### LINKED ISSUE #186: Make XCMError more detailed
## Issue summary

As testing XCM calls in #160, the provided `XCMError` is helpless for debugging

Should we just extend the Xcm Error to the target pallet's error definition?

Suggest to write a proc-macro for extending `#[pallet:error]` with `XcmError`

## Other information and links

-

### LINKED ISSUE #200: Extend xcm errors with proc-macro
## Issue summary

Extends xcm errors to custom pallet errors

## Other information and links
-

### PR DESCRIPTION
**Pull request by clearloop**
## Changes

`#[xcm_error]` to extend custom pallet errors with xcm errors

## Tests

```
CI
```

## Issues

Closes #200 
Closes #186

### CODE REVIEW

**Comment by mattsse** [comment]
fyi: https://docs.rs/synstructure/0.12.5/synstructure/

also can you elaborate on the intended functionality, afaik, pallet errors can't have fields?

**Comment by clearloop** [comment]
> afaik, pallet errors can't have fields?

yep

**Comment by clearloop** [comment]
Hard to use proc-macro to expand `Error<T>` because of the limit of `#[pallet::error]` (`#[pallet::error]` is an attribute of `#[pallet]`, the execution order of attribute macro sucks),

I'd like to 
* hard code the XCMErrors into `Error<T>`
* try custom functional-macro 

How do you like these ideas? @mattsse

**Comment by mattsse** [comment]
> Hard to use proc-macro to expand `Error<T>` because of the limit of `#[pallet::error]` (`#[pallet::error]` is an attribute of `#[pallet]`, the execution order of attribute macro sucks),
> 
> I'd like to
> 
> * hard code the XCMErrors into `Error<T>`
> * try custom functional-macro
> 
> How do you like these ideas? @mattsse, I think it's really important of supporting all Errors in XCM for debugging the unstable XCM calls ( I hate XCM calls LOL)

yeah this is rather unpleasant to work with, so I'd propose to bit this on hold for now. not much we can do at the moment

**Review by clearloop — COMMENTED** [review]
I don't think we need this macro anymore after #161, keep this only if we need convert XcmErrors in pallets

**Review by mattsse — APPROVED** [review]
LGTM,
even though we can't directly put it use yet, my guess would be that this will come in handy if need to refactor transacting xcm calls

**Pull request merged**
